const AFFILIATE_URL = 'https://rdr.fmcgsd.net/in/offer/3424?aid=78767';
const products = [
  {category:'plants', ru:{name:'Монстера Deliciosa',desc:'Графичный акцент для светлой комнаты'},uk:{name:'Монстера Deliciosa',desc:'Графічний акцент для світлої кімнати'},price:'от 590 ₴',image:'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=700&q=80',tag:'best'},
  {category:'bouquets', ru:{name:'Букет «Тёплый свет»',desc:'Розы, ранункулюсы и лёгкое настроение'},uk:{name:'Букет «Тепле світло»',desc:'Троянди, ранункулюси та легкий настрій'},price:'от 1 290 ₴',image:'https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=700&q=80',tag:'new'},
  {category:'garden', ru:{name:'Набор для террасы',desc:'Травы и цветы для первого урожая'},uk:{name:'Набір для тераси',desc:'Трави та квіти для першого врожаю'},price:'от 780 ₴',image:'https://images.unsplash.com/photo-1591857177580-dc82b9ac4e1e?auto=format&fit=crop&w=700&q=80',tag:'season'},
  {category:'gifts', ru:{name:'Green Box «Спасибо»',desc:'Растение, открытка и забота в одной коробке'},uk:{name:'Green Box «Дякую»',desc:'Рослина, листівка та турбота в одній коробці'},price:'от 950 ₴',image:'https://images.unsplash.com/photo-1526397751294-331021109fbd?auto=format&fit=crop&w=700&q=80',tag:'gift'},
  {category:'plants', ru:{name:'Фикус эластика',desc:'Спокойная форма для большого пространства'},uk:{name:'Фікус еластика',desc:'Спокійна форма для великого простору'},price:'от 690 ₴',image:'https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=700&q=80',tag:'best'},
  {category:'bouquets', ru:{name:'Композиция «Точка света»',desc:'Минималистичный букет в керамике'},uk:{name:'Композиція «Точка світла»',desc:'Мінімалістичний букет у кераміці'},price:'от 1 450 ₴',image:'https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=700&q=80',tag:'new'},
  {category:'garden', ru:{name:'Семена душистых трав',desc:'Базилик, мята и чабрец на подоконнике'},uk:{name:'Насіння запашних трав',desc:'Базилік, м’ята та чебрець на підвіконні'},price:'от 120 ₴',image:'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=700&q=80',tag:'season'},
  {category:'gifts', ru:{name:'Арома-набор «Пауза»',desc:'Свеча, диффузор и 20 минут для себя'},uk:{name:'Арома-набір «Пауза»',desc:'Свічка, дифузор та 20 хвилин для себе'},price:'от 640 ₴',image:'https://images.unsplash.com/photo-1603006905003-be475563bc59?auto=format&fit=crop&w=700&q=80',tag:'gift'}
];
const translations = {
  ru:{navCatalog:'Каталог',navSeason:'Сезон',navJournal:'Журнал',headerCta:'Выбрать подарок ↗',eyebrow:'Актуально для Украины · 2025/26',heroLine1:'Живые идеи',heroLine2:'для нового ритма.',heroLead:'Растения, букеты и подарки, которые превращают обычный день в личное событие. Собрали лучшее от Florium.ua в одном умном каталоге.',heroButton:'Смотреть каталог ↓',heroSecondary:'Гид по сезону ↗',proof:'4.9 / 5',proofCaption:'выбор покупателей',floatingTitle:'Найдено для вас',floatingText:'12 сезонных идей',seasonEyebrow:'Сезонный радар · сегодня',seasonTitle:'Лето—Осень: время добавить цвета',seasonText:'С 10 июня по 10 декабря выбираем устойчивые растения, солнечные букеты и подарки с характером.',catalogEyebrow:'Кураторская полка / 01',catalogTitle:'Выберите свой вайб',catalogIntro:'Не бесконечный маркетплейс, а короткий список вещей, которые действительно хочется подарить.',searchPlaceholder:'Поиск по каталогу…',filterAll:'Все',filterPlants:'Растения',filterBouquets:'Букеты',filterGarden:'Сад',filterGifts:'Подарки',emptyState:'Ничего не нашли — попробуйте другое слово.',promoTitle:'Сезонные скидки,<br><em>которые успевают.</em>',promoText:'Подберём свежую идею под повод, бюджет и город доставки. Спецпредложения меняются вместе с сезоном.',promoCta:'Забрать предложение ↗',journalEyebrow:'Florium journal / 02',journalTitle:'Маленькие ритуалы,<br>большое настроение.',journalLink:'Все материалы ↗',storyTag1:'Уход',storyTitle1:'Как вернуть зелени энергию после жаркого лета',storyText1:'Три простых шага для листьев, которые снова хотят сиять.',storyTag2:'Идеи',storyTitle2:'Подарок, который говорит за вас',storyTag3:'Сезон',storyTitle3:'Зима—Весна: что посадить первым',readMore:'Читать 4 мин ↗',footerText:'Партнёрский каталог для тех, кто выбирает живое.',footerCta:'Перейти на Florium.ua ↗',affiliateNote:'Партнёрская подборка · цены и наличие уточняйте на сайте продавца'},
  uk:{navCatalog:'Каталог',navSeason:'Сезон',navJournal:'Журнал',headerCta:'Обрати подарунок ↗',eyebrow:'Актуально для України · 2025/26',heroLine1:'Живі ідеї',heroLine2:'для нового ритму.',heroLead:'Рослини, букети та подарунки, які перетворюють звичайний день на особливу подію. Зібрали найкраще від Florium.ua в одному розумному каталозі.',heroButton:'Дивитися каталог ↓',heroSecondary:'Гід сезоном ↗',proof:'4.9 / 5',proofCaption:'вибір покупців',floatingTitle:'Знайдено для вас',floatingText:'12 сезонних ідей',seasonEyebrow:'Сезонний радар · сьогодні',seasonTitle:'Літо—Осінь: час додати кольору',seasonText:'З 10 червня до 10 грудня обираємо витривалі рослини, сонячні букети та подарунки з характером.',catalogEyebrow:'Кураторська полиця / 01',catalogTitle:'Оберіть свій вайб',catalogIntro:'Не нескінченний маркетплейс, а короткий список речей, які справді хочеться подарувати.',searchPlaceholder:'Пошук у каталозі…',filterAll:'Усі',filterPlants:'Рослини',filterBouquets:'Букети',filterGarden:'Сад',filterGifts:'Подарунки',emptyState:'Нічого не знайшли — спробуйте інше слово.',promoTitle:'Сезонні знижки,<br><em>які встигають.</em>',promoText:'Підберемо свіжу ідею під привід, бюджет і місто доставки. Спецпропозиції змінюються разом із сезоном.',promoCta:'Забрати пропозицію ↗',journalEyebrow:'Florium journal / 02',journalTitle:'Маленькі ритуали,<br>великий настрій.',journalLink:'Усі матеріали ↗',storyTag1:'Догляд',storyTitle1:'Як повернути зелені енергію після спекотного літа',storyText1:'Три прості кроки для листя, яке знову хоче сяяти.',storyTag2:'Ідеї',storyTitle2:'Подарунок, який скаже все за вас',storyTag3:'Сезон',storyTitle3:'Зима—Весна: що посадити першим',readMore:'Читати 4 хв ↗',footerText:'Партнерський каталог для тих, хто обирає живе.',footerCta:'Перейти на Florium.ua ↗',affiliateNote:'Партнерська добірка · ціни та наявність уточнюйте на сайті продавця'}
};
Object.assign(translations.ru,{shipping:'Стандартная доставка по Украине · 30 дней на возврат',shipping2:'Сезонные предложения Florium.ua уже здесь',feature1Tag:'Бестселлеры',feature1Title:'Растения<br>для здоровья',feature2Tag:'Топ товары',feature2Title:'Растения<br>для дома',feature3Tag:'Высокий рейтинг',feature3Title:'Растения<br>для офиса',shopNow:'В магазин →',catalogLink:'Смотреть весь каталог →'});
Object.assign(translations.uk,{shipping:'Стандартна доставка по Україні · 30 днів на повернення',shipping2:'Сезонні пропозиції Florium.ua вже тут',feature1Tag:'Бестселери',feature1Title:'Рослини<br>для здоров’я',feature2Tag:'Топ товари',feature2Title:'Рослини<br>для дому',feature3Tag:'Високий рейтинг',feature3Title:'Рослини<br>для офісу',shopNow:'До магазину →',catalogLink:'Дивитися весь каталог →'});
Object.assign(translations.ru,{seoTitle:'Растения и цветы с доставкой по Украине',seoText:'Смотрите комнатные растения, садовые цветы, букеты, семена и подарки для Киева, Львова, Одессы, Днепра, Харькова и других городов Украины. Перед покупкой проверяйте актуальные цены, наличие и условия доставки на официальном сайте Florium.ua.',seoDisclosure:'Партнёрский каталог: переход по ссылке может принести автору комиссию.'});
Object.assign(translations.uk,{seoTitle:'Рослини та квіти з доставкою по Україні',seoText:'Переглядайте кімнатні рослини, садові квіти, букети, насіння та подарунки для Києва, Львова, Одеси, Дніпра, Харкова й інших міст України. Перед покупкою перевіряйте актуальні ціни, наявність і умови доставки на офіційному сайті Florium.ua.',seoDisclosure:'Партнерський каталог: перехід за посиланням може принести автору комісію.'});
let locale = 'ru', activeFilter = 'all';
const grid = document.querySelector('#productGrid'), search = document.querySelector('#search');
function renderProducts(){const term=search.value.trim().toLowerCase();const list=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(!term||`${p[locale].name} ${p[locale].desc}`.toLowerCase().includes(term)));grid.innerHTML=list.map((p,i)=>`<article class="product-card"><a href="${AFFILIATE_URL}" target="_blank" rel="nofollow sponsored noopener" aria-label="${p[locale].name}"><div class="product-visual">${i%3!==1?`<span class="discount">-${10+i*3}%</span>`:''}<span class="heart" aria-hidden="true">♡</span><img loading="lazy" src="${p.image}" alt="${p[locale].name}" width="700" height="700"></div></a><div class="product-info"><h3>${p[locale].name}</h3><p>${p[locale].desc}</p><div class="product-price"><del>${p.price}</del> <strong>${p.price.replace('от ','').replace(' ', ' ')}</strong></div><div class="rating"><span>★★★★★</span> 4.5 (2)</div></div></article>`).join('');document.querySelector('#emptyState').hidden=list.length>0}
function setLocale(next){locale=next;document.documentElement.lang=next==='uk'?'uk':'ru';document.querySelectorAll('[data-i18n]').forEach(el=>{if(translations[next][el.dataset.i18n]!==undefined)el.innerHTML=translations[next][el.dataset.i18n]});document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=translations[next][el.dataset.i18nPlaceholder]);document.querySelector('.lang-active').textContent=next==='ru'?'RU':'UA';renderProducts();localStorage.setItem('florium-locale',next)}
document.querySelectorAll('.filter').forEach(btn=>btn.addEventListener('click',()=>{document.querySelector('.filter.active').classList.remove('active');btn.classList.add('active');activeFilter=btn.dataset.filter;renderProducts()}));search.addEventListener('input',renderProducts);document.querySelector('.lang-switch').addEventListener('click',()=>setLocale(locale==='ru'?'uk':'ru'));const requestedLocale=new URLSearchParams(location.search).get('lang');setLocale(requestedLocale==='uk'||localStorage.getItem('florium-locale')==='uk'?'uk':'ru');renderProducts();
